language: objective-c

osx_image: xcode10

xcode_project: ios-app-on-travis.xcodeproj

xcode_scheme: ios-app-on-travisTests

env:
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone X"
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=11.0.1,name=iPhone 8"
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone SE"

jobs:
    include:
        - stage: scan
          script: true
          notifications:
            slack:
              secure: "n0lrsx4Z8Dl/bSopksZ3PiHwhi+SrcBwoTjmZpLVCe2YRDp12k2v0uNLjlHEYtJOb08txperfpZthY5ihoLFbQZhJ41w5h3SE4/3xHA05ZCS2Cq+l8NdnqK6TxkFtfh6ksS2OVfHelJUH1ohXjU3dGhZAfuFlyUdyTgS256gaeOpuWrjwkkyQJadlfUTu44AQGA55HRFbkNReEjT3HayKkG9V9vV7cTsR2FHx5xN4HNiWAe/i6PFWZuFOgK7AUTFsBA4FS/r4AoVepE+5SONpm+XA43Nmo3NYOf2416DTTKl0pzijaRDPVf1e50LzvivVidwZdVMgyzfvv+c2+hbw3DZKd/X1HEbhLmCwjR3JnbQMy4FvI2nFM+Odh2DWwAtoE3r2U6hXiCi/zXZjECQaTmHWsNzluGjTrnEGJBkbutHTBnXvz29V8by9i7a+MflRtbtanxlDg8HWKa3Rb+VwpNK9XckH/Anz7RaYU+NgUN3SpH3vuXxngFldF/9wqgBqUHWAXFhtMGWASGLTIuShZBJ1oPClDvW1L0dP2XrCf3kvg2BrecrCMLlOiSL3uCWj8X+wx8lpaza1rJQShZreLGaDP9EkFIPfnl6SZBwUttLBKp3kvBlMJ8v98dLa9PEtYDMvlCcIPA0m+sKo69wFdu8mI2gu+wvHXpq4OgMMCI="
        - stage: deploy
          env: DEVICE_NAME=iPhone X OS=12.0
          script:
              - echo 'deploying...'
              - echo 'deploy finished!'

stages:
  - test
  - scan
  - name: deploy
    if: branch IN (master)

before_install: echo 'before_install...'

install: echo 'install...'

before_script: echo 'before_script...'

script: xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk iphonesimulator -destination "$XCTEST_DESTINATION" test

after_success: echo 'after_success...'
