language: objective-c
osx_image: xcode10
xcode_project: ios-app-on-travis.xcodeproj
xcode_scheme: ios-app-on-travisTests

jobs:
    include:
        - stage: test
          script: xcodebuild -project ios-app-on-travis.xcodeproj -scheme ios-app-on-travisTests -sdk iphonesimulator test
        - stage: deploy
          if: branch = master
          script: echo 'deploying...'
