language: objective-c
osx_image: xcode10
xcode_project: ios-app-on-travis.xcodeproj
xcode_scheme: ios-app-on-travisTests

jobs:
    include:
        - script: xcodebuild -project ios-app-on-travis.xcodeproj -scheme ios-app-on-travisTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' test
        - script: xcodebuild -project ios-app-on-travis.xcodeproj -scheme ios-app-on-travisTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0.1' test
        - script: xcodebuild -project ios-app-on-travis.xcodeproj -scheme ios-app-on-travisTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' test
        - stage: deploy
          if: branch = master
          script: echo 'deploying...'

stages:
  - test
  - name: deploy
    if: branch != master

before_install: echo 'before_install...'
install: echo 'install...'
before_script: echo 'before_script...'
script: echo 'script...'
after_success: echo 'after_success...'
