language: objective-c

osx_image: xcode10

xcode_project: ios-app-on-travis.xcodeproj

xcode_scheme: ios-app-on-travisTests

env:
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone X"
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=11.0.1,name=iPhone 8"
  - XCTEST_DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone SE"

jobs:
    include:
        - stage: deploy
          env: DEVICE_NAME=iPhone X OS=12.0
          script:
              - echo 'deploying...'
              - echo 'deploy finished!'

stages:
  - test
  - name: deploy
    if: branch IN (master)

before_install: echo 'before_install...'

install: echo 'install...'

before_script: echo 'before_script...'

script: xcodebuild -project TRAVIS_XCODE_PROJECT -scheme TRAVIS_XCODE_SCHEME -sdk iphonesimulator -destination "$XCTEST_DESTINATION" test

after_success: echo 'after_success...'
